use_frameworks!

target 'SSNetwork_Example' do
  platform :ios, '7.0'
  pod 'SSNetwork', :path => '../'

  target 'SSNetwork_Tests' do
    inherit! :search_paths
    platform :ios, '7.0'
    pod 'FBSnapshotTestCase'
  end
  
end
platform :ios, '7.0'
pod 'AFNetworking'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '7.0'
        end
    end
end